project:
  type: website

website:
  title: "kagstat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: HAHA
      - href: pres.qmd
        text: Presentations
    right:
    - text: CV
    - href: KAG_Resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

